config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index' 

  resources :lists do
    resources :items
  end
  resources :items

  patch '/items/:id', to: 'items#update'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :content

  def checked?
    completed == true
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
  validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :sanitize_content, only: [:edit, :update]
  # GET /items
  # GET /items.json
  def index
    new 
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new

  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    sanitize_content

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
        format.js
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(update_params)
        format.html { render :show, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully deleted.' }
      format.json { head :no_content }
      format.js
    end
  end

  def sanitize_content
    #binding.pry
    if /<.*((script)|(href)|(src)).*>/.match(@item.content) != nil
      @item.content = "<i>Item contained illegal tags</i>"
    else
      @item.content
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:content, :completed, :list_id)
    end

    def update_params
      params.permit(:content, :completed)
    end
end

app/controllers/lists_controller.rb
require 'pry'

class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @item = Item.new 
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find_by_id(params[:id])
    @items = @list.items

    respond_to do |format| 
      format.html 
      format.js
    end
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
        format.js
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(update_params)
        format.html { render :edit, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @destroy_id = @list.id
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :color)
    end
    def update_params
      params.permit(:title, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<i class="material-icons icon add_item_button">add</i>
<section class='new-item-form'>
  <%= form_for(item = Item.new, remote: true) do |f| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label "New item:" %><br>
      <%= f.text_area :content %>
      
      <% this_id ||= nil %>
      <%= f.hidden_field :list_id, :value => this_id %>
    </div>
    <div class="actions">
      <%= f.submit 'Add item' %>
    </div>
  <% end %>
</section>

app/views/items/_item.html.erb
<section id='<%="item#{item.id}"%>' class="<% if item.checked? %> 
               <%= 'completed item-row' %>
               <% else %>
               <%= 'item-row' %>
               <% end %> ">

  <%= check_box_tag('completed', 'completed', item.completed) %>
  
  <%= link_to item, method: :delete, remote: true  do %>
    <i class="material-icons float-right icon">clear</i>
  <% end %>

  <%= link_to item do %>
    <%= item.content ? item.content.html_safe : ''%>
  <% end %>
  <script>
    var context = $('#item<%= item.id %> input[type=checkbox]');
    addToggleCompleted('<%= item.id %>', context);
  </script>
</section>
  

app/views/items/create.js.erb
<% this_list = @item.list_id %>
<% this_list ||= '' %>
$('#list<%=this_list%>').append('<%=j render @item %>');
$('.new_item').trigger('reset');

app/views/items/destroy.js.erb
$("#item<%=@item.id%>").remove();

app/views/items/edit.html.erb
<section class='list'>
  <h1>Editing Item</h1>

  <%= render @item %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
</section>

app/views/items/index.html.erb
<section class='list'>

  <h2>All Items</h2>
  <p id="notice"><%= notice %></p>

  <%= render 'form' %>

  <section class='list' id='list'>
    <%= render @items %>
   </section>
</section>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<section class="list">
  <p>
    <strong>Content:</strong>
    <%= @item.content %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= @item.completed %>
  </p>

  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag     'https://fonts.googleapis.com/icon?family=Material+Icons' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= link_to 'View All Lists', lists_path %> &bullet;
    <%= link_to 'View All Items', items_path %>
  </header>
  <section id='wrapper'>

    <%= yield %>

    <footer>
     Tyler Korthal &copy; <%= Time.new().year %>
    </footer>
  </section>
</body>
</html>

app/views/lists/_form.html.erb
<% list = List.new %>
<%= form_for(list, remote: true) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class='list'>
    <div class="field">
      <%= f.label 'New List' %><br>
      <%= f.text_field :title %>
    </div>
    <div class="actions">
      <%= f.submit "Add list" %>
    </div>
  </section>
<% end %>

app/views/lists/_list.html.erb
<section class='list' id='<%="list#{list.id}" %>'>
  <h2>
    <%= link_to list, method: :delete, remote: true do %>
      <i class="material-icons  icon">clear</i>
     <% end %>
    <%= link_to list.title, list_path(list) %> 
  </h2>

  <%= render 'items/form', this_id: list.id %>
  <% list.items.each do |item| %>
    <%= render item %>
  <% end %>
  <script>
    addItemListeners('<%= list.id %>');
    $('#list<%= list.id %>').css("background-color", '<%= list.color %>');
  </script>
</section>

app/views/lists/create.js.erb
$('#lists').append('<%=j render @list %>');

app/views/lists/destroy.js.erb
<% element_to_destroy = "#list#{@destroy_id}"%>
$("<%=element_to_destroy%>").remove();

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Lists</h1>
  <section id='lists'>
    <%= render @lists %>
  </section>
<%= render 'form' %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<section id='list<%= @list.id %>' class='list'>

  <h1><%= @list.title %></h1>
  <p id="notice"><%= notice %><input type='color' id='bgColor'></p>

  <script>
    $("#bgColor").on('change', function (){
      updateBGColor('<%= @list.id %>', $("#bgColor").val());
    });
  </script>
  <section id='new-item-form'>
    <%= render 'items/form', this_id: @list.id %>
  </section>

  <script>
    var listId = '<%= @list.id %>';
    addItemListeners(listId);
  </script>

  <section class='item-list'>
    <%= render @items %>
  </section>
  <script>
    $('#list<%= @list.id %>').css("background-color", '<%= @list.color %>');
  </script>
</section>